[toolchain]
anchor_version = "0.31.1"
solana_version = "2.1.18"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
snake_contract = "GkRRA3Jhds6sxDr89wMneCjNDDmHof2zqnHdjaqP7kGU"

[programs.devnet]
snake_contract = "Aw4zQtbMuxCChXS923HeyhAMPakC8KMQa6tQmMS4pPYM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/user_role_registry_tests.ts tests/patron_framework.ts tests/vesting_OTCswap.ts"

[workspace]
members = [
  "programs/snake_contract"
]
