[toolchain]
anchor_version = "0.31.1"
solana_version = "2.1.18"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
snake_contract = "CLhbCetmpAFowhsKJM9XDJ5AWgkiDUmNPJV7CTZzFDsL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/super/.config/solana/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/user_role_registry_tests.ts tests/patron_framework.ts tests/vesting_OTCswap.ts"

[workspace]
members = [
  "programs/snake_contract"
]

[profile.release]
opt-level = "z"

[build]
programs = { snake_contract = "target/deploy/snake_contract-keypair.json" }
