[toolchain]
anchor_version = "0.31.1"
solana_version = "2.1.18"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
snake_contract = "A75BhFuMiJoe3bwNXAJbsPykKSQfvVhC5oYH9k9X6RQy"

[programs.localnet]
snake_contract = "BWzCm61AEgjSrRvinG4HEiNdVhLPabsPqvEPG96AN2pL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/super/.config/solana/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/otc_swap_enhanced.ts"

[workspace]
members = [
  "programs/snake_contract"
]

[profile.release]
opt-level = "z"

[build]
programs = { snake_contract = "target/deploy/snake_contract-keypair.json" }
