[package]
name = "server"
version.workspace = true
edition.workspace = true

[dependencies]
axum.workspace = true
database.path = "../database"
hyper.workspace = true
tokio.workspace = true
tower-http.workspace = true
utils.path = "../libraries/utils"
